version: '3.1'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'verdaccio'
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './.data/storage:/verdaccio/storage'
      - './.data/config:/verdaccio/conf'
      - './.data/plugins:/verdaccio/plugins'
